version: '1.0'

services:
  backend:
    build: ./TourAssist-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/TourAssist
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypassword
      FRONTEND_URL: http://localhost:5173


  frontend:
    build: ./TourAssist-frontend
    ports:
      - "5173:5173"
    environment:
      ENV: development

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: TourAssist
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
