spring:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  datasource:
#    url: jdbc:mysql://localhost:3306/TourAssist
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      secret-key: idr7T5JBeraYvPQWcrtj5RLxdak43JJlUd0OTghkzUc=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

storage:
  cloud-name: dnm5uzsbl
  access-key: 854872313461948
  secret-key: e2gLOFlmFp_S9OVkzkL6nzNoWrQ

cors:
  url: ${FRONTEND_URL}